import { AppProviders } from '@/components/shared/AppProviders';
import { fonts } from '@/utils/fonts';
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import { extractRouterConfig } from 'uploadthing/server';
import { ourFileRouter } from './api/uploadthing/core';
import './globals.css';

export const metadata: Metadata = {
  title: 'Imaginarium',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={fonts.inter}>
        <AppProviders>
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          {children}
          <Toaster richColors />
        </AppProviders>
      </body>
    </html>
  );
}
